#pragma config(Sensor, dgtl1,  upLimit,        sensorTouch)
#pragma config(Sensor, dgtl2,  downLimit,      sensorTouch)
#pragma config(Motor,  port1,           leftFrontMotor, tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           leftBackMotor, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightFrontMotor, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           rightBackMotor, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           liftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setMotorPower(tMotor motorToSet, TVexJoysticks channel, int deadzone = 20)
{
	motor[motorToSet] = abs(channel) > deadzone ? channel : 0;

	//if(abs(channel) > deadzone)
	//{
	//	motor[motorToSet] = channel;
	//}
	//else
	//{
	//	motor[motorToSet] = 0;
	//}
}

void tankDrive()
{
	setMotorPower(leftFrontMotor, vexRT[Ch3]);
	setMotorPower(leftBackMotor, vexRT[Ch3]);
	setMotorPower(rightFrontMotor, vexRT[Ch2]);
	setMotorPower(rightBackMotor, vexRT[Ch2]);
}

bool hitLimit = false;
int time = 0;

void liftControl()
{
	//TODO: Make this work
	int outputVal = 0;
	if (vexRT[Btn5D])
	{
		outputVal = -60;
	}
	else if (vexRT[Btn5U])
	{
		outputVal = 75;
	}
	else
	{
		outputVal = 0;
	}

	if (SensorValue[downLimit] == 1 && outputVal < 0)
	{
		//hitLimit = true;
		//time1[T1] = 0;
		outputVal = 0;
	}
	else if (SensorValue[upLimit] == 1 && outputVal > 0)
	{
		//hitLimit = false;
		outputVal = 0;
	}

	/*
	if (hitLimit)
	{
		outputVal = 10;
	}

	if (time1[T1] > 500)
	{
		hitLimit = false;
	}
	*/

	motor[liftMotor] = outputVal;
}

task main()
{
	time1[T1] = 0;
	while(true)
	{
		tankDrive();
		liftControl();
	}
}
