#pragma config(Sensor, port3,  light,          sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port7,  sonar,          sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumper,         sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move (int leftMotorPower, int rightMotorPower, int time)
{
	motor [leftMotor] = leftMotorPower;
	motor [rightMotor] = rightMotorPower;
	wait1Msec(time);
}

task main()
{
	motor[motor10] = 100;
	move(75,-75, 1300);
	move(-100, -100, 0);
	while(SensorValue[sonar] > 500)
	{
		displayTextLine(1, "Sonar: %d", SensorValue[sonar]);
	}
	move(0,0,1000000);





}
