#pragma config(Sensor, port9,  color,          sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move (int leftmotorPower, int rightmotorPower, int time)
{
	motor [leftMotor] = leftmotorPower;
	motor [rightMotor] = rightmotorPower;
	wait1Msec(time);
}



task main()
{
	move(100,100, 250);

	move(0,0,500);

	move(100,-100,300);

	while(true)
	{


		if(SensorValue[color] > 100)
		{
			move(100,0,0);
		}
		else
		{
			move(0,100,0);
		}
	}
}
