#pragma config(Sensor, port9,  color,          sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move (int leftmotorPower, int rightmotorPower, int time)
{
	motor [leftMotor] = leftMotorPower;
	motor [rightMotor] = rightMotorPower;
	wait1Msec(time);
}

void moveEncoder(int leftmotorPower, int rightmotorPower, int distance)
{
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

	motor[leftMotor] = leftmotorPower;
	motor[rightMotor] = rightmotorPower;

while ( abs(nMotorEncoder[leftMotor])< distance && abs(nMotorEncoder[rightMotor]) < distance )
	{

	}
	move(0,0,0);
}

task main()
{
	moveEncoder(100,35,220);

	moveEncoder(35,100,475);

	moveEncoder(30,30,5);


	move(0,0,3000);

	moveEncoder(75,100,1000);

	moveEncoder(100,10,375);

	moveEncoder(100,100, 2000);
}
