#pragma config(Sensor, port9,  color,          sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move (int leftMotorPower, int rightMotorPower, int time)
{
	motor [leftMotor] = leftMotorPower;
	motor [rightMotor] = rightMotorPower;
	wait1Msec(time);
	motor [leftMotor] = 0;
	motor [rightMotor] = 0;
}

void MoveEncoder(int leftmotorPower, int rightmotorPower, int distance)
{
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

	motor[leftMotor] = leftmotorPower;
	motor[rightMotor] = rightmotorPower;

	while(abs(nMotorEncoder[leftMotor]) < distance && abs(nMotorEncoder[rightMotor]) < distance)
	{
	}
	move(0,0,0);
}

void moveClaw(int power, int time)
{
	motor[clawMotor] = power;
	wait1Msec(time);
	motor[clawMotor] = 0;
}

void moveArm(int power, int time)
{
	motor[armMotor] = power;
	wait1Msec(time);
	motor[armMotor] = 0;
}

void moveUntilColor(int leftmotorPower, int rightmotorPower, int grayscale)
{
	motor [leftMotor] = 100;
	motor [rightMotor] = 100;

	while(SensorValue[color] > grayscale )
	{

	}
	move(0,0,0);
}




task main()
{
	int maxDistance = SensorValue[port7];

	motor [leftMotor] = 0;
	motor [rightMotor] = 0;

	while(true)
	{
		moveUntilColor(100,100,32);
		move(100,100,500);
		int distance = nMotorEncoder[leftMotor];
		MoveEncoder(-100,-100, distance);
		MoveEncoder(100,100,distance);


	}
}

/*for(int power = 0; power < 101; power ++)
{
move(power,power,50);
}

for(int power = 99;power > 0; power --)
{
move(power,power,50);
}

for(int i = 0; i < 101; i++)
{

}
/*

}


}

/*
moveClaw(100, 1000);
moveClaw(-100, 1000);

move(100,100,2600);

move(0,0,1000);

moveArm(-100, 130);

moveArm(0, 1000);

moveClaw(100, 250);

moveClaw(0,1000);

moveArm(100, 500);

move(-100, -100, 400);

move(-100,-20, 500);

move(100, 80, 4500);

move(50, 100, 600);

moveClaw(-100, 7500);
*/
