#pragma config(Sensor, port4,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,           ,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,           ,             tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetGyro(gyro);

	while(abs(getGyroDegrees(gyro)) < 180)
	{
		motor[motor1] = 100;
		motor[motor6] = -100;
	}

	motor[motor1] = 0;
	motor[motor6] = 0;

}
